/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package alta.sql.CP_GENERAL;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author LCE X - XX
 */
public class ObjetosANDreportes extends javax.swing.JFrame {

    /**
     * Creates new form ObjetosANDreportes
     */
    
    //"INSERT INTO op (ID_OP, NAME_OP, DESC_OP, LUGAR_OP, EST_OP) VALUES (?, ?, ?, ?, ?)";
    public ObjetosANDreportes() {
        initComponents();
        OTRO.setEnabled(false);
        RPZ.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NOM1 = new javax.swing.JTextField();
        DES1 = new javax.swing.JTextField();
        UBIC1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        ZRP = new javax.swing.JComboBox<>();
        OTRO = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        RPID = new javax.swing.JTextField();
        RPUS = new javax.swing.JTextField();
        RPZ = new javax.swing.JTextField();
        ST1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        canvas1 = new java.awt.Canvas();
        URL = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("REPORTE DE PERDIDA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 150, 60));

        jLabel2.setText("OBJETO ENCONTRADO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 160, 50));

        NOM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NOM1ActionPerformed(evt);
            }
        });
        getContentPane().add(NOM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 180, -1));

        DES1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DES1ActionPerformed(evt);
            }
        });
        getContentPane().add(DES1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 180, 50));

        UBIC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UBIC1ActionPerformed(evt);
            }
        });
        getContentPane().add(UBIC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 180, -1));

        jButton1.setText("ENVIAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 79, -1));

        ZRP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Azucares", "Hangar", "Bodega", "Contaduria", "Post procesos", "Backend", "Otro" }));
        ZRP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ZRPMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ZRPMouseExited(evt);
            }
        });
        ZRP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZRPActionPerformed(evt);
            }
        });
        getContentPane().add(ZRP, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 130, -1));

        OTRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OTROActionPerformed(evt);
            }
        });
        getContentPane().add(OTRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 190, -1));

        jLabel3.setText("en caso de otro:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 90, 20));

        jLabel4.setText("ID");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, -1, -1));

        jLabel5.setText("NOMBRE");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, 20));

        jLabel6.setText("Descripcion");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 70, 20));

        jLabel7.setText("Estado: :V");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 70, 20));

        jLabel8.setText("Ubicacion");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 70, 20));

        RPID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RPIDActionPerformed(evt);
            }
        });
        getContentPane().add(RPID, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 180, -1));

        RPUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RPUSActionPerformed(evt);
            }
        });
        getContentPane().add(RPUS, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 180, -1));

        RPZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RPZActionPerformed(evt);
            }
        });
        getContentPane().add(RPZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 180, 50));

        ST1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buen estado", "Dañado", "Destruido", "Otro" }));
        ST1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ST1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ST1MouseExited(evt);
            }
        });
        ST1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ST1ActionPerformed(evt);
            }
        });
        getContentPane().add(ST1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 130, -1));

        jLabel10.setText("En caso de otro:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, 90, -1));

        jLabel11.setText("Username");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 70, -1));

        jLabel12.setText("Zona de trabajo");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 90, -1));

        jButton2.setText("Enviar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, -1, -1));

        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(255, 0, 0));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("X");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(612, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 60));
        getContentPane().add(canvas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, -1, -1));

        URL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                URLActionPerformed(evt);
            }
        });
        getContentPane().add(URL, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 230, 60));

        jLabel9.setText("URL IMAGEN:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 120, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DES1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DES1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DES1ActionPerformed

    private void UBIC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UBIC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UBIC1ActionPerformed

    private void OTROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OTROActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OTROActionPerformed

    private void ZRPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZRPActionPerformed
        // TODO add your handling code here:
          Chequeo2();
    }//GEN-LAST:event_ZRPActionPerformed
private void Chequeo(){
  String opt= ST1.getSelectedItem().toString();
        if(opt.equals("Otro")){
        OTRO.setEnabled(true);
        }else{
            OTRO.setEnabled(false);
        }
}

private void Chequeo2(){
  String opt= ZRP.getSelectedItem().toString();
        if(opt.equals("Otro")){
        RPZ.setEnabled(true);
        }else{
        RPZ.setEnabled(false);
        }
}


//UPDATE nombre tabla SET 
    private void ZRPMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ZRPMouseExited
        // TODO add your handling code here:
        Chequeo2();

    }//GEN-LAST:event_ZRPMouseExited

    private void ZRPMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ZRPMouseEntered
        // TODO add your handling code here:
        Chequeo2();
    }//GEN-LAST:event_ZRPMouseEntered
 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String VopST="";
     
       
        String VopNM = NOM1.getText();
        System.out.println(VopNM);
         String VopDC = DES1.getText();
        System.out.println(VopDC);
         String VopUB = UBIC1.getText();
        System.out.println(VopUB);
        if(ST1.getSelectedItem()== "Otro"){
      VopST = OTRO.getText();
          System.out.println(VopST); 
        }else{
       VopST = ST1.getSelectedItem().toString();
        System.out.println(VopST); 
        }
        String VopURL=URL.getText();
        Connection cn = null;
        PreparedStatement pst = null;
         try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            cn = DriverManager.getConnection("jdbc:mysql://localhost/cosasperdidas", "root", "");
            System.out.println("Conectado");

            String query = "INSERT INTO op (NAME_OP, DESC_OP, LUGAR_OP, EST_OP, IMG_OP_URL) VALUES  (?, ?, ?, ?,?)";
            pst = cn.prepareStatement(query);
           
            pst.setString(1, VopNM);
            pst.setString(2, VopDC);
            pst.setString(3, VopUB);
            pst.setString(4, VopST);
            pst.setString(5, VopURL);
            
            System.out.println(pst);

           pst.executeUpdate();
           
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ALTASQL.class.getName()).log(Level.SEVERE, "Error al cargar el driver", ex);
        } catch (SQLException ex) {
            Logger.getLogger(ALTASQL.class.getName()).log(Level.SEVERE, "Error en la base de datos", ex);
        } finally {
            try {
                if (pst != null) pst.close();
                if (cn != null) cn.close();
            } catch (SQLException e) {
                Logger.getLogger(ALTASQL.class.getName()).log(Level.SEVERE, "Error al cerrar recursos", e);
            }
        }
        
/*-- Start a transaction to ensure atomicity
S-- Start a transaction to ensure atomicity
START TRANSACTION;

-- Retrieve the maximum ID from the op table
SET @max_id = (SELECT IFNULL(MAX(ID_OP), 0) FROM op);

-- Calculate the next auto-increment value
SET @next_auto_increment = @max_id + 1;

-- Alter the table to set the auto-increment value
SET @sql = CONCAT('ALTER TABLE op AUTO_INCREMENT = ', @next_auto_increment);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- Commit the transaction
COMMIT;
         */
    }//GEN-LAST:event_jButton1ActionPerformed

    private void NOM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NOM1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NOM1ActionPerformed

    private void RPIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RPIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RPIDActionPerformed

    private void RPUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RPUSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RPUSActionPerformed

    private void RPZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RPZActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RPZActionPerformed

    private void ST1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ST1MouseEntered
        // TODO add your handling code here:
        Chequeo();
    }//GEN-LAST:event_ST1MouseEntered

    private void ST1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ST1MouseExited
        // TODO add your handling code here:
        Chequeo();
    }//GEN-LAST:event_ST1MouseExited

    private void ST1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ST1ActionPerformed
        // TODO add your handling code here:
          Chequeo();
    }//GEN-LAST:event_ST1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int VrpID= Integer.parseInt(RPID.getText());
        System.out.println(VrpID);
        String VrpUSER = RPUS.getText();
        System.out.println(VrpUSER);
        String VrpZn = "";
        if(ZRP.getSelectedItem() == "Otro"){
            VrpZn = RPZ.getText();
        System.out.println(VrpZn);
        }else{
          VrpZn = ZRP.getSelectedItem().toString();
        System.out.println(VrpZn); 
        }
        
        Connection cn= null;
        PreparedStatement pst= null;
            try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            cn = DriverManager.getConnection("jdbc:mysql://localhost/cosasperdidas", "root", "");
            System.out.println("Conectado");

            String query = "INSERT INTO rp (ID_RP,USER_RP,CNTC_RP) VALUES (?, ?, ?)";
            pst = cn.prepareStatement(query);
            pst.setInt(1, VrpID);
            pst.setString(2, VrpUSER);
            pst.setString(3, VrpZn);
            


           pst.executeUpdate();
           
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ALTASQL.class.getName()).log(Level.SEVERE, "Error al cargar el driver", ex);
        } catch (SQLException ex) {
            Logger.getLogger(ALTASQL.class.getName()).log(Level.SEVERE, "Error en la base de datos", ex);
        } finally {
            try {
                if (pst != null) pst.close();
                if (cn != null) cn.close();
            } catch (SQLException e) {
                Logger.getLogger(ALTASQL.class.getName()).log(Level.SEVERE, "Error al cerrar recursos", e);
            }
                   
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel13MouseEntered

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void URLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_URLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_URLActionPerformed
int xMouse, yMouse;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ObjetosANDreportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ObjetosANDreportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ObjetosANDreportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ObjetosANDreportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ObjetosANDreportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DES1;
    private javax.swing.JTextField NOM1;
    private javax.swing.JTextField OTRO;
    private javax.swing.JTextField RPID;
    private javax.swing.JTextField RPUS;
    private javax.swing.JTextField RPZ;
    private javax.swing.JComboBox<String> ST1;
    private javax.swing.JTextField UBIC1;
    private javax.swing.JTextField URL;
    private javax.swing.JComboBox<String> ZRP;
    private java.awt.Canvas canvas1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
